services:
  postgres:
    image: postgres:18
    container_name: pingboard-postgres
    environment:
      POSTGRES_USER: ping
      POSTGRES_PASSWORD: ping
      POSTGRES_DB: pingboard
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql

volumes:
  pgdata:
